---
collections:
  - name: ansible.utils
    version: '*'
  - name: ansible.posix
  - name: awx.awx
  - name: community.aws
  - name: community.crypto
  - name: community.general
  - name: community.libvirt
  - name: kubernetes.core
  - name: containers.podman
  - name: infra.osbuild
  - name: redhat_cop.controller_configuration
  - name: fedora.linux_system_roles
  - name: https://github.com/rprakashg/vpac.git,main
    type: git